#!/bin/bash

if [ $# -eq 0 ]
then
read -p "Dati calea" spmd
else
spmd=$1
fi

if [ ! -f $spmd -o ! -x $spmd ]
then
echo "Eroare"
exit 1
fi

shift

if [ $# -eq 0 ]
then
read -p "Dati n: " n
else 
n=$1
fi

if [ ! $n -gt 0 ]
then
echo "Eroare"
exit 2
fi

shift

declare -a val

for i in `seq 1 $n`
do
if  [ $# -eq 0 ]
then 
read -p "Dati val[$i]: " val[$i]
else
val[$i]=$1
shift
fi
done

for i in `seq 1 $n`
do
$spmd ${val[$i]} &
done
echo "Parallel Spmd started"
wait

echo "Parallel spmd finished"

